### PR TITLE
WIP: Respect repository priority ordering

### PR DESCRIPTION
**Pull request by GloriousEggroll**
Respect repository priority ordering when providing available package updates

Resolves https://github.com/timlau/yumex-ng/issues/50

### CODE REVIEW

**Comment by timlau** [comment]
Thanks for the pull request.

I have some issues with the code.
- Running dnf(4) command line in the doing screen scraping of the output works, but introduce a lot of stuff there can break if something changes in the output of the dnf command and if the user run a another locale this output will be translated and the code will break.
- One of my design choices is to only using public dnf4 & dnf5 API to get information about packages and repositories, so this kind of actions should be implemented using the dnf5/dnf4 api, not by running command line commands in the background.
- dnf5 back-end must not depend on dnf4 and the dnf5 configmanager  is not the same as dnf4
-

**Comment by GloriousEggroll** [comment]
rather than scraping the output it can likely be converted into a key based array. the exact same lines and values are printed regardless of language. Ex:
```
[nobara-baseos-40]
bandwidth = 0
baseurl = 
cachedir = /var/tmp/dnf-tcrider-mcd45h7f
cost = 1000
countme = 0
deltarpm = 0
deltarpm_percentage = 75
enabled = 1
enabled_metadata = 1
enablegroups = 1
exclude = 
excludepkgs = 
fastestmirror = 0
gpgcheck = 1
gpgkey = file:///etc/pki/rpm-gpg/RPM-GPG-KEY-nobara-baseos-pubkey-40-x86_64
includepkgs = 
ip_resolve = whatever
max_downloads_per_mirror = 3
max_parallel_downloads = 6
mediaid = 
metadata_expire = 172800
minrate = 1000
mirrorlist = https://mirrors.nobaraproject.org/baseos
module_hotfixes = 0
name = nobara-baseos-40
password = 
priority = 50
protected_packages = dnf, grub2-efi-ia32, grub2-efi-x64, grub2-pc, grub2-tools-minimal, sudo, systemd, systemd-udev, shim-aa64, shim-arm, shim-ia32, shim-x64, nobara-welcome, nobara-nvidia-wizard, nobara-login, nobara-release, nobara-repos, fedora-repos, plasma-desktop, setup
proxy = 
proxy_auth_method = any
proxy_sslcacert = 
proxy_sslclientcert = 
proxy_sslclientkey = 
proxy_sslverify = 1
repo_gpgcheck = 0
retries = 10
skip_if_unavailable = 1
sslcacert = 
sslclientcert = 
sslclientkey = 
sslverify = 1
sslverifystatus = 0
throttle = 0
timeout = 30
type = rpm-md
user_agent = libdnf (Nobara Linux 40; kde; Linux.x86_64)
username = 
```

In the case of locale and scraping we could instead just fetch it by key number e.g.:

```
import subprocess

# Step 1: Execute the command and capture its output
command_output = subprocess.check_output("dnf config-manager --dump \"nobara-baseos-40\"", shell=True).decode('utf-8')

# Step 2 & 3: Parse the output and store fields and values in a dictionary
config_dict = {}
for line in command_output.split('\n'):
    if '=' in line:
        key, value = line.strip().split('=', 1)
        config_dict[key] = value

# Step 4: Convert the dictionary items to a list of tuples
config_list = list(config_dict.items())

# Function to fetch a field's value by its index in the list
def get_value_by_index(index):
    try:
        return config_list[index][1]  # Return the value part of the tuple
    except IndexError:
        return None

# Example usage
index_to_fetch = 5  # Example index
value = get_value_by_index(index_to_fetch)
print(f"Value at index {index_to_fetch}: {value}")
```

Of course we would need to rework running a subprocess for the DNF command to actually using the dnf4/5 api and also work out the dnf5 config-manager changes, but this would be at least a way to work around the locale issue with scraping

**Comment by GloriousEggroll** [comment]
I also verified config-manager dump outputs the exact same fields and does not translate them when setting LANG:

$ LANG=es_ES.utf8 dnf config-manager --dump "nobara-baseos-40"
$ LANG=fr_FR.utf8 dnf config-manager --dump "nobara-baseos-40"

**Comment by GloriousEggroll** [comment]
It looks like the main issue would be not with the config-manager but with the dnf provides output:
```
$ LANG=fr_FR.UTF8 dnf provides kwin

kwin-6.0.5-2.fc40.x86_64 : KDE Window manager
Dépôt               : nobara-baseos-40
Correspondances trouvées dans  :
Fournir : kwin = 6.0.5-2.fc40

kwin-6.0.5-3.fc40.x86_64 : KDE Window manager
Dépôt               : updates
Correspondances trouvées dans  :
Fournir : kwin = 6.0.5-3.fc40
```

So in this case we could do the numerical key based thing instead.

**Comment by GloriousEggroll** [comment]
Actually I've found a much much easier way to implement this using dnf4/5 apis:

```
    def get_repo_priority(self, repo_name: str) -> int:
    """Fetches the priority of a specified repository using DNF4 API."""
    repo = self.repos.get(repo_name)
    if repo:
        return repo.priority
    else:
        # Return a default value if the repository name was not found
        return 99

    def get_package_repos(self, package_name: str) -> List[str]:
        """Fetches the repositories providing a given package using DNF4 API."""
        repos = set()
        query = self.sack.query().available().filter(name=package_name)
        for pkg in query.run():
            repos.add(pkg.reponame)
        return list(repos)
```

**Comment by timlau** [comment]
I have updated the current backend get_repositories to also return priority for the repos
https://github.com/timlau/yumex-ng/commit/85442d6d29ee272d072dd3fc57de6b0ab7299244

**Comment by timlau** [comment]
Checked you repository, the current approach looks much better :-)

**Comment by timlau** [comment]
fixed some minor issues after merge, so it don't blow up when using the dnf5 back end.
I have no prioritized repos, so can't test that it does the right thing

**Comment by GloriousEggroll** [comment]
Thanks sorry it was 4 am by the time I responded on this, needed some sleep, I'll double check with dnf4 and 5

**Comment by GloriousEggroll** [comment]
DNF4 is working, something's up with DNF5. Looking into it now

**Pull request merged**
